name: Build Debian Packages with Debcraft
run-name: Building ${{ github.event.inputs.hosting }} - ${{ github.event.inputs.gh_repo }}@${{ github.event.inputs.gh_ref }}
on:
  workflow_dispatch:
    inputs:
      gh_repo:
        description: 'Github Repository to build, specify as simple <owner>/<repo-name>'
        required: true
        default: 'centic9/mtools-ppa'
      gh_ref:
        description: 'Which branch or tag to build'
        required: true
        default: 'ppa/4.0.43-1'
      hosting:
        description: 'Specify salsa if gh_repo and gh_ref point to a repository on the Debian Salsa hosting platform or codeberg for hosting on codeberg.org'
        required: false
        default: 'github'
      debcraft_repo:
        description: Allows to test with a different version of the Debcraft tool
        required: false
        # https://github.com/ottok/debcraft
        default: 'ottok/debcraft'
      debcraft_ref:
        description: Allows to test with a different version of the Debcraft tool
        required: false
        default: '3a5c6518d5f780466991af5920442a07d1cff8c8'

jobs:
  build-debs:
    name: Build ${{ matrix.codename }}-${{ matrix.arch }} of ${{ github.event.inputs.gh_repo }}@${{ github.event.inputs.gh_ref }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        codename: [bookworm, trixie, forky, sid, noble]
        # , arm64, armhf
        arch: [amd64]
    steps:
      - name: checkout package sources of ${{ github.event.inputs.gh_repo }}@${{ github.event.inputs.gh_ref }} on ${{ matrix.codename }}-${{ matrix.arch }} with Hosting ${{ github.event.inputs.hosting }}
        uses: actions/checkout@v4
        id: checkout-github
        with:
          repository: ${{ github.event.inputs.gh_repo }}
          path: repo
          ref: ${{ github.event.inputs.gh_ref }}
          # this is required for gbp to work properly
          fetch-tags: true
          # not sure why this was needed, fetch-tags should fetch the necessary refs, but somehow did not
          fetch-depth: 0
        if: ${{ github.event.inputs.hosting == 'github' }}

      - name: checkout package sources of ${{ github.event.inputs.gh_repo }}@${{ github.event.inputs.gh_ref }} on ${{ matrix.codename }}-${{ matrix.arch }} with Salsa ${{ github.event.inputs.hosting }}
        id: checkout-salsa
        # Removed "--depth=1" as otherwise some of the git-commands used by debcraft and gbp will fail
        # the checkout-action does this somehow, but I could not yet find out how this can be done with git commands directly
        run: |
          set -eu
          git clone --branch ${{ github.event.inputs.gh_ref }} https://salsa.debian.org/${{ github.event.inputs.gh_repo }}.git repo
          cd repo
          echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        if: ${{ github.event.inputs.hosting == 'salsa' }}

      - name: checkout package sources of ${{ github.event.inputs.gh_repo }}@${{ github.event.inputs.gh_ref }} on ${{ matrix.codename }}-${{ matrix.arch }} with Github ${{ github.event.inputs.hosting }}
        id: checkout-codeberg
        # Removed "--depth=1" as otherwise some of the git-commands used by debcraft and gbp will fail
        # the checkout-action does this somehow, but I could not yet find out how this can be done with git commands directly
        run: |
          set -eu
          git clone --branch ${{ github.event.inputs.gh_ref }} https://codeberg.org/${{ github.event.inputs.gh_repo }}.git repo
          cd repo
          echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        if: ${{ github.event.inputs.hosting == 'codeberg' }}

      - name: checkout debcraft
        id: checkout-debcraft
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.debcraft_repo }}
          path: debcraft
          ref: ${{ github.event.inputs.debcraft_ref }}

      - name: install required software
        run: sudo apt install -y make podman

      - name: install debcraft
        working-directory: debcraft
        run: make install-local

      - name: run build
        working-directory: repo
        run: $HOME/.local/bin/debcraft build --distribution ${{ matrix.codename }}

      - name: Build artifact name
        id: artifact-name
        run: echo "ARTIFACT_NAME=${{ matrix.codename }}@${{ matrix.arch }}@${{ github.event.inputs.gh_repo }}@${{ github.event.inputs.gh_ref }}@${{ steps.checkout-github.outputs.commit }}${{ steps.checkout-salsa.outputs.commit }}${{ steps.checkout-codeberg.outputs.commit }}" | sed -e 's:/:_:g' >> "$GITHUB_OUTPUT"

      - name: save binary artifact
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact-name.outputs.ARTIFACT_NAME }}
          path: debcraft-build-*/
